<a href="https://colab.research.google.com/github/aizaaziz/aizaaziz-DataScience-GenAI-Submissions/blob/main/Copy_of_2_01_data_and_feature_engineering_in_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![](https://drive.google.com/uc?export=view&id=1xqQczl0FG-qtNA2_WQYuWePW9oU8irqJ)

# Data and Feature Engineering
This Notebook will introduce us to preparing our datasets for data science and AI workloads. For sturctured data, this will often utilise popular Python libraries such as Pandas, which will be the focus for this Notebook.

### What is Pandas?
As Python has grown to become a popular solution for data analysis, many new tools have been introduced to support such tasks. Pandas is arguably the most popular and widely used of these, although it does have some limitations (if working with very large datasets you may want to look at Dask and/or PySpark).

First, we will import it into our session. This effectively means we have opened the library in the background, and can now use the [functions](https://github.com/MJMortensonWarwick/IB2AD0_Data_Science_GenerativeAI/blob/main/1_10_functions.ipynb) built into it. We will also import numpy - another widely used Python package for working with numerical data (the name is a portmanteau of "numerical" and "python"). By convention we import pandas as "pd" and numpy as "np". This is equivalent to giving it a variable name.

In [ ]:
import pandas as pd
import numpy as np

### Testing our installation
To test everything is working we will create some fake data frame using numpy and load it into a pandas dataframe (more on these below). First we will create the random numbers:

In [ ]:
x = np.random.rand(10,1)
x

array([[0.6739113 ],
       [0.15659947],
       [0.36373803],
       [0.89064537],
       [0.14067151],
       [0.46853167],
       [0.23171027],
       [0.14824743],
       [0.94468339],
       [0.09016272]])

The commands here have told numpy to create a set of random numbers between zero and one. The arguments we have passed, "1" and "10", tells numpy we want a 10x1 array of numbers (i.e. a table (more accurately a vector) with 10 rows and 1 column).

Next we will create a pandas dataframe using "x":

In [ ]:
testdf = pd.DataFrame(x)
testdf

          0
0  0.673911
1  0.156599
2  0.363738
3  0.890645
4  0.140672
5  0.468532
6  0.231710
7  0.148247
8  0.944683
9  0.090163

We have now successfully created a pandas dataframe!

### What are Dataframes?
Pandas has a very elegant way of managing data, very much borrowed from the statistical language R, mostly based around dataframes. You can think of dataframes a bit like an Excel table with rows, columns and common operations like sum, average and so on. We can use this on top of our previous work on lists and dictionaries (etc.) more usable and malleable.

To begin with we will create a dataset - in this case a [dictionary](https://github.com/MJMortensonWarwick/IB2AD0_Data_Science_GenerativeAI/blob/main/1_05_dictionaries.ipynb).

In [ ]:
orders = {'o10001':{'date':'2024/01/10', 'product':'Hoodie', 'quantity':'1'},
            'o10002':{'date':'2024/01/13', 'product':'Tote bag', 'quantity':'2'},
            'o10003':{'date':'2024/01/14', 'product':'Pencil', 'quantity':'10'},
            'o10004':{'date':'2024/01/15', 'product':'T-shirt', 'quantity':'2'}
}
orders

{'o10001': {'date': '2024/01/10', 'product': 'Hoodie', 'quantity': '1'},
 'o10002': {'date': '2024/01/13', 'product': 'Tote bag', 'quantity': '2'},
 'o10003': {'date': '2024/01/14', 'product': 'Pencil', 'quantity': '10'},
 'o10004': {'date': '2024/01/15', 'product': 'T-shirt', 'quantity': '2'}}

We can convert this to a Dataframe with great ease

In [ ]:
import pandas as pd
import numpy as np

orders_df = pd.DataFrame(orders)
orders_df

              o10001      o10002      o10003      o10004
date      2024/01/10  2024/01/13  2024/01/14  2024/01/15
product       Hoodie    Tote bag      Pencil     T-shirt
quantity           1           2          10           2

We can even create such outputs from more complex dictionaries, such as a dictionary which includes a nested list:

In [ ]:
customers = {'Mark':{'name':'Mark Johnson', 'open_orders':3, 'orders':['o10001', 'o10002', 'o10004']},
             'Katy':{'name':'Katy Hoad', 'open_orders':0, 'orders':[]},
             'Angela':{'name':'Angela Lorenz', 'open_orders':1, 'orders':['o10003']},
             'Bo':{'name':'Bo Kelestyn', 'open_orders':0, 'orders':[]}
}
customers

{'Mark': {'name': 'Mark Johnson',
  'open_orders': 3,
  'orders': ['o10001', 'o10002', 'o10004']},
 'Katy': {'name': 'Katy Hoad', 'open_orders': 0, 'orders': []},
 'Angela': {'name': 'Angela Lorenz', 'open_orders': 1, 'orders': ['o10003']},
 'Bo': {'name': 'Bo Kelestyn', 'open_orders': 0, 'orders': []}}

In [ ]:
customers_df = pd.DataFrame(customers)
customers_df

                                 Mark       Katy         Angela           Bo
name                     Mark Johnson  Katy Hoad  Angela Lorenz  Bo Kelestyn
open_orders                         3          0              1            0
orders       [o10001, o10002, o10004]         []       [o10003]           []

Pandas dataframes can also be built from various other data structures and sources (including Excel files, CSVs, text files, databases and many more). For example, we can make our dataframe from a set of [lists](https://github.com/MJMortensonWarwick/IB2AD0_Data_Science_GenerativeAI/blob/main/1_04_lists.ipynb):

In [ ]:
a = [1, 2, 3, 4]
b = ["a", "b", "c", "d"]
c = [True, False, True, False]

listdf = pd.DataFrame([a, b, c])
listdf

      0      1     2      3
0     1      2     3      4
1     a      b     c      d
2  True  False  True  False

### EXERCISE
Try building you own dataframes from a list and/or dictionary you create. What would happen if you have an item missing from one element. E.g. if "c" in the above example only had three items - True, False, True - rather than four. Test it - does the output match your expectation?

# My notes/summary:

Pandas is a data analysis library → mainly used for structured data

Import convention → import pandas as pd, import numpy as np

DataFrames are table-like → rows + columns (similar to Excel)

Create DataFrames easily → from arrays, lists, or dictionaries

Works with nested data → dictionaries containing lists or dicts

Used for data prep → cleaning, organising, analysing data for AI/DS

In [ ]:
a_new = [10, 20, 30, 40]
b_new = ["apple", "banana", "cherry", "date"]
c_short = [True, False] # This list now has 2 items, unlike the others which have 4

# Create a DataFrame from these lists
df_from_unequal_lists = pd.DataFrame([a_new, b_new, c_short])
df_from_unequal_lists

       0       1       2     3
0     10      20      30    40
1  apple  banana  cherry  date
2   True   False    True  None

# My Expectations:
I created a DataFrame using lists where one list had fewer items than the others.

Pandas still created the DataFrame, but it filled the missing value with **None**. This happens because Pandas expects all rows to line up, so when data is missing it automatically inserts an **empty value** instead of throwing an error.

This **matched** my expectation once I saw how Pandas deal with missing data.

# This is to double check the outcome:

My expectations matched the outcome.

In [ ]:
a_new_v2 = [10, 20, 30, 40]
b_new_v2 = ["apple", "banana", "cherry", "date"]
c_short_v2 = [True, False] # This list now has 2 items, unlike the others which have 4

# Create a DataFrame from these lists
df_from_unequal_lists_v2 = pd.DataFrame([a_new_v2, b_new_v2, c_short_v2])
df_from_unequal_lists_v2

       0       1       2     3
0     10      20      30    40
1  apple  banana  cherry  date
2   True   False    None  None